version: '3'

services:
  #########################################
  # Database
  #########################################
  psql:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME

  #########################################
  # Storage
  #########################################
  s3:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - asset_s3_data:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_REGION_NAME
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  #########################################
  # Redis service
  #########################################
  redis:
    image: bitnami/redis:6.2
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

volumes:
  asset_s3_data:
